name: CD Pipeline

on:
  workflow_run: 
    workflows: ["CI Pipeline"]
    types: 
     - completed

jobs:

  build:

    runs-on: ubuntu-latest

    steps:  
    - name: Deploy to prod
      uses: appleboy/ssh-action@master
      id: deploy-prod
      if: contains(github.ref, 'main')
      with:
        host: ${{ secrets.HOST_PROD }} # EC2 퍼블릭 IPv4 DNS
        username: ubuntu
        key: ${{ secrets.PRIVATE_KEY }} #ssh pk(?)
        envs: GITHUB_SHA
        script: |
          sudo docker pull haileythegooner/klaytn_alert:latest
          sudo docker rm -f klaytn_alert-container || true 
          sudo docker image prune -f
          
          echo "DISCORD_WEBHOOK_URL=${{secrets.DISCORD_WEBHOOK_URL}}" >> .env.production
          echo "DISCORD_URL=${{secrets.DISCORD_URL}}" >> .env.production
          echo "DISCORD_TOKEN=${{secrets.DISCORD_TOKEN}}" >> .env.production
          echo "DISCORD_CHANNELID=${{secrets.DISCORD_CHANNELID}}" >> .env.production

          echo "wsUrl_klaytn=${{secrets.wsUrl_klaytn}}" >> .env.production
          echo "wsUrl_wemix=${{secrets.wsUrl_wemix}}" >> .env.production

          echo "Threshold_KLAY=${{secrets.Threshold_KLAY}}" >> .env.production
          echo "Threshold_WEMIX=${{secrets.Threshold_WEMIX}}" >> .env.production
          echo "Threshold_MBX=${{secrets.Threshold_MBX}}" >> .env.production
          echo "Threshold_BORA=${{secrets.Threshold_BORA}}" >> .env.production
          echo "Threshold_GHUB=${{secrets.Threshold_GHUB}}" >> .env.production
          echo "Threshold_KLEVA=${{secrets.Threshold_KLEVA}}" >> .env.production
          echo "Threshold_SSX=${{secrets.Threshold_SSX}}" >> .env.production
          echo "Threshold_PLA=${{secrets.Threshold_PLA}}" >> .env.production

          echo "APP_KEY=${{secrets.APP_KEY}}" >> .env.production
          echo "APP_SECRET=${{secrets.APP_SECRET}}" >> .env.production
          echo "BEARER_TOKEN=${{secrets.BEARER_TOKEN}}" >> .env.production
          echo "ACCESS_TOKEN=${{secrets.ACCESS_TOKEN}}" >> .env.production
          echo "ACCESS_SECRET=${{secrets.ACCESS_SECRET}}" >> .env.production
          echo "CLIENT_ID=${{secrets.CLIENT_ID}}"  >> .env.production 
          echo "CLIENT_SECRET=${{secrets.CLIENT_SECRET}}"  >> .env.production
          
          echo "TELEGRAM_TOKEN=${{secrets.TELEGRAM_TOKEN}}" >> .env.production
          echo "NGROK_SEVER_URL=${{secrets.NGROK_SEVER_URL}}" >> .env.production
      
          echo "WSETHURL=${{secrets.WSETHURL}}" >> .env.production
          echo "DB_URL=${{secrets.DB_URL}}" >> .env.production
          echo "COINMARKETCAP=${{secrets.COINMARKETCAP}}" >> .env.production

          sudo docker run --env-file ./.env.production -d -p 8080:8080 --name klaytn_alert-container haileythegooner/klaytn_alert

      
      
